language: android
dist: trusty

before_install:
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30.0.3"

notifications:
  slack:
    rooms:
      - supla:dauFpwhgEGeyy9ERzqOYeJyY#github

android:
  components:
    - build-tools-30.0.2
    - android-30
    - extra
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
