package org.supla.core.shared.infrastructure
/*
 Copyright (C) AC SOFTWARE SP. Z O.O.

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

enum class LocalizedStringId {
  GENERAL_TURN_ON,
  GENERAL_TURN_OFF,
  GENERAL_OPEN,
  GENERAL_CLOSE,
  GENERAL_OPEN_CLOSE,
  GENERAL_SHUT,
  GENERAL_REVEAL,
  GENERAL_COLLAPSE,
  GENERAL_EXPAND,

  GENERAL_YES,
  GENERAL_NO,

  CHANNEL_CAPTION_OPEN_SENSOR_GATEWAY,
  CHANNEL_CAPTION_CONTROLLING_THE_GATEWAY_LOCK,
  CHANNEL_CAPTION_OPEN_SENSOR_GATE,
  CHANNEL_CAPTION_CONTROLLING_THE_GATE,
  CHANNEL_CAPTION_OPEN_SENSOR_GARAGE_DOOR,
  CHANNEL_CAPTION_CONTROLLING_THE_GARAGE_DOOR,
  CHANNEL_CAPTION_OPEN_SENSOR_DOOR,
  CHANNEL_CAPTION_CONTROLLING_THE_DOOR_LOCK,
  CHANNEL_CAPTION_OPEN_SENSOR_ROLLER_SHUTTER,
  CHANNEL_CAPTION_OPEN_SENSOR_ROOF_WINDOW,
  CHANNEL_CAPTION_CONTROLLING_THE_ROLLER_SHUTTER,
  CHANNEL_CAPTION_CONTROLLING_THE_ROOF_WINDOW,
  CHANNEL_CAPTION_CONTROLLING_THE_FACADE_BLIND,
  CHANNEL_CAPTION_POWER_SWITCH,
  CHANNEL_CAPTION_LIGHTSWITCH,
  CHANNEL_CAPTION_THERMOMETER,
  CHANNEL_CAPTION_HUMIDITY,
  CHANNEL_CAPTION_HUMIDITY_AND_TEMPERATURE,
  CHANNEL_CAPTION_WIND_SENSOR,
  CHANNEL_CAPTION_PRESSURE_SENSOR,
  CHANNEL_CAPTION_RAIN_SENSOR,
  CHANNEL_CAPTION_WEIGHT_SENSOR,
  CHANNEL_CAPTION_NO_LIQUID_SENSOR,
  CHANNEL_CAPTION_DIMMER,
  CHANNEL_CAPTION_RGB_LIGHTING,
  CHANNEL_CAPTION_DIMMER_AND_RGB_LIGHTING,
  CHANNEL_CAPTION_DEPTH_SENSOR,
  CHANNEL_CAPTION_DISTANCE_SENSOR,
  CHANNEL_CAPTION_OPENING_SENSOR_WINDOW,
  CHANNEL_CAPTION_HOTEL_CARD_SENSOR,
  CHANNEL_CAPTION_ALARM_ARMAMENT_SENSOR,
  CHANNEL_CAPTION_MAIL_SENSOR,
  CHANNEL_CAPTION_STAIRCASE_TIMER,
  CHANNEL_CAPTION_IC_GAS_METER,
  CHANNEL_CAPTION_IC_WATER_METER,
  CHANNEL_CAPTION_IC_HEAT_METER,
  CHANNEL_CAPTION_THERMOSTAT_HEATPOL_HOMEPLUS,
  CHANNEL_CAPTION_VALVE,
  CHANNEL_CAPTION_GENERAL_PURPOSE_MEASUREMENT,
  CHANNEL_CAPTION_GENERAL_PURPOSE_METER,
  CHANNEL_CAPTION_THERMOSTAT,
  CHANNEL_CAPTION_ELECTRICITY_METER,
  CHANNEL_CAPTION_DIGIGLASS,
  CHANNEL_CAPTION_TERRACE_AWNING,
  CHANNEL_CAPTION_PROJECTOR_SCREEN,
  CHANNEL_CAPTION_CURTAIN,
  CHANNEL_CAPTION_VERTICAL_BLIND,
  CHANNEL_CAPTION_ROLLER_GARAGE_DOOR,
  CHANNEL_CAPTION_PUMP_SWITCH,
  CHANNEL_CAPTION_HEAT_OR_COLD_SOURCE_SWITCH,
  CHANNEL_CAPTION_UNKNOWN,

  CHANNEL_BATTERY_LEVEL,

  MOTOR_PROBLEM,
  CALIBRATION_LOST,
  CALIBRATION_FAILED,

  THERMOSTAT_THERMOMETER_ERROR,
  THERMOSTAT_BATTER_COVER_OPEN,
  THERMOSTAT_CLOCK_ERROR
}
