package org.supla.core.shared.infrastructure
/*
 Copyright (C) AC SOFTWARE SP. Z O.O.

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

enum class LocalizedStringId {
  GENERAL_TURN_ON,
  GENERAL_TURN_OFF,
  GENERAL_OPEN,
  GENERAL_CLOSE,
  GENERAL_OPEN_CLOSE,
  GENERAL_SHUT,
  GENERAL_REVEAL,
  GENERAL_COLLAPSE,
  GENERAL_EXPAND,

  GENERAL_YES,
  GENERAL_NO,

  CHANNEL_CAPTION_OPEN_SENSOR_GATEWAY,
  CHANNEL_CAPTION_CONTROLLING_THE_GATEWAY_LOCK,
  CHANNEL_CAPTION_OPEN_SENSOR_GATE,
  CHANNEL_CAPTION_CONTROLLING_THE_GATE,
  CHANNEL_CAPTION_OPEN_SENSOR_GARAGE_DOOR,
  CHANNEL_CAPTION_CONTROLLING_THE_GARAGE_DOOR,
  CHANNEL_CAPTION_OPEN_SENSOR_DOOR,
  CHANNEL_CAPTION_CONTROLLING_THE_DOOR_LOCK,
  CHANNEL_CAPTION_OPEN_SENSOR_ROLLER_SHUTTER,
  CHANNEL_CAPTION_OPEN_SENSOR_ROOF_WINDOW,
  CHANNEL_CAPTION_CONTROLLING_THE_ROLLER_SHUTTER,
  CHANNEL_CAPTION_CONTROLLING_THE_ROOF_WINDOW,
  CHANNEL_CAPTION_CONTROLLING_THE_FACADE_BLIND,
  CHANNEL_CAPTION_POWER_SWITCH,
  CHANNEL_CAPTION_LIGHTSWITCH,
  CHANNEL_CAPTION_THERMOMETER,
  CHANNEL_CAPTION_HUMIDITY,
  CHANNEL_CAPTION_HUMIDITY_AND_TEMPERATURE,
  CHANNEL_CAPTION_WIND_SENSOR,
  CHANNEL_CAPTION_PRESSURE_SENSOR,
  CHANNEL_CAPTION_RAIN_SENSOR,
  CHANNEL_CAPTION_WEIGHT_SENSOR,
  CHANNEL_CAPTION_NO_LIQUID_SENSOR,
  CHANNEL_CAPTION_DIMMER,
  CHANNEL_CAPTION_RGB_LIGHTING,
  CHANNEL_CAPTION_DIMMER_AND_RGB_LIGHTING,
  CHANNEL_CAPTION_DEPTH_SENSOR,
  CHANNEL_CAPTION_DISTANCE_SENSOR,
  CHANNEL_CAPTION_OPENING_SENSOR_WINDOW,
  CHANNEL_CAPTION_HOTEL_CARD_SENSOR,
  CHANNEL_CAPTION_ALARM_ARMAMENT_SENSOR,
  CHANNEL_CAPTION_MAIL_SENSOR,
  CHANNEL_CAPTION_STAIRCASE_TIMER,
  CHANNEL_CAPTION_IC_GAS_METER,
  CHANNEL_CAPTION_IC_WATER_METER,
  CHANNEL_CAPTION_IC_HEAT_METER,
  CHANNEL_CAPTION_THERMOSTAT_HEATPOL_HOMEPLUS,
  CHANNEL_CAPTION_VALVE,
  CHANNEL_CAPTION_GENERAL_PURPOSE_MEASUREMENT,
  CHANNEL_CAPTION_GENERAL_PURPOSE_METER,
  CHANNEL_CAPTION_THERMOSTAT,
  CHANNEL_CAPTION_ELECTRICITY_METER,
  CHANNEL_CAPTION_DIGIGLASS,
  CHANNEL_CAPTION_TERRACE_AWNING,
  CHANNEL_CAPTION_PROJECTOR_SCREEN,
  CHANNEL_CAPTION_CURTAIN,
  CHANNEL_CAPTION_VERTICAL_BLIND,
  CHANNEL_CAPTION_ROLLER_GARAGE_DOOR,
  CHANNEL_CAPTION_PUMP_SWITCH,
  CHANNEL_CAPTION_HEAT_OR_COLD_SOURCE_SWITCH,
  CHANNEL_CAPTION_UNKNOWN,
  CHANNEL_CAPTION_CONTAINER,
  CHANNEL_CAPTION_SEPTIC_TANK,
  CHANNEL_CAPTION_WATER_TANK,
  CHANNEL_CAPTION_CONTAINER_LEVEL_SENSOR,
  CHANNEL_CAPTION_FLOOD_SENSOR,
  CHANNEL_CAPTION_MOTION_SENSOR,
  CHANNEL_CAPTION_BINARY_SENSOR,

  CHANNEL_STATUS_AWAITING,
  CHANNEL_STATUS_UPDATING,
  CHANNEL_STATUS_NOT_AVAILABLE,

  CHANNEL_BATTERY_LEVEL,

  MOTOR_PROBLEM,
  CALIBRATION_LOST,
  CALIBRATION_FAILED,

  OVERCURRENT_WARNING,

  THERMOSTAT_THERMOMETER_ERROR,
  THERMOSTAT_BATTER_COVER_OPEN,
  THERMOSTAT_CLOCK_ERROR,
  THERMOSTAT_CALIBRATION_ERROR,

  FLOOD_SENSOR_ACTIVE,
  VALVE_MANUALLY_CLOSED,
  VALVE_FLOODING,
  VALVE_MOTOR_PROBLEM,
  VALVE_SENSOR_OFFLINE,

  CONTAINER_ALARM_LEVEL,
  CONTAINER_WARNING_LEVEL,
  CONTAINER_INVALID_SENSOR_STATE,
  CONTAINER_SOUND_ALARM,

  // Add wizard
  DEVICE_REGISTRATION_REQUEST_TIMEOUT,
  ENABLING_REGISTRATION_TIMEOUT,
  ADD_WIZARD_SCAN_TIMEOUT,
  ADD_WIZARD_DEVICE_NOT_FOUND,
  ADD_WIZARD_CONNECT_TIMEOUT,
  ADD_WIZARD_CONFIGURE_TIMEOUT,
  ADD_WIZARD_WIFI_ERROR,
  ADD_WIZARD_RESULT_NOT_COMPATIBLE,
  ADD_WIZARD_RESULT_CONNECTION_ERROR,
  ADD_WIZARD_RESULT_FAILED,
  ADD_WIZARD_RECONNECT_TIMEOUT,
  ADD_WIZARD_DEVICE_TEMPORARILY_LOCKED,
  ADD_WIZARD_STATE_PREPARING,
  ADD_WIZARD_STATE_CONNECTING,
  ADD_WIZARD_STATE_CONFIGURING,
  ADD_WIZARD_STATE_FINISHING,

  // State
  CHANNEL_STATE_UPTIME,
  CHANNEL_STATE_BATTERY_POWERED,
  CHANNEL_STATE_MAINS_POWERED,
  LAST_CONNECTION_RESET_CAUSE_UNKNOWN,
  LAST_CONNECTION_RESET_CAUSE_ACTIVITY_TIMEOUT,
  LAST_CONNECTION_RESET_CAUSE_WIFI_CONNECTION_LOST,
  LAST_CONNECTION_RESET_CAUSE_SERVER_CONNECTION_LOST,

  // Result code
  RESULT_CODE_TEMPORARILY_UNAVAILABLE,
  RESULT_CODE_CLIENT_LIMIT_EXCEEDED,
  RESULT_CODE_DEVICE_DISABLED,
  RESULT_CODE_ACCESS_ID_DISABLED,
  RESULT_CODE_REGISTRATION_DISABLED,
  RESULT_CODE_ACCESS_ID_NOT_ASSIGNED,
  RESULT_CODE_INACTIVE,
  RESULT_CODE_INCORRECT_EMAIL_OR_PASSWORD,
  RESULT_CODE_BAD_CREDENTIALS,
  RESULT_CODE_UNKNOWN_ERROR,

  LIFESPAN_WARNING_REPLACE,
  LIFESPAN_WARNING_SCHEDULE,
  LIFESPAN_WARNING,

  DIGIGLASS_PLANNED_REGENERATION,
  DIGIGLASS_REGENERATION_AFTER_20H,
  DIGIGLASS_TO_LONG_OPERATION
}
